In [8]:
import numpy as np
array = np.array([[1,2,3],
                  [2,3,4]])
array

array([[1, 2, 3],
       [2, 3, 4]])

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [3]:
print(array)

[[1 2 3]
 [2 3 4]]


In [4]:
data = np.zeros((3,4))
data

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
data = np.ones((3,4))
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
data = np.empty((3,3))
data

array([[ 6.17779239e-31, -1.23555848e-30,  3.08889620e-31],
       [-1.23555848e-30,  2.68733969e-30, -8.34001973e-31],
       [ 3.08889620e-31, -8.34001973e-31,  4.78778910e-31]])

In [7]:
data = np.linspace(1,20,5) # 生成线段
data

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [8]:
data = np.arange(1,20,5)
data

array([ 1,  6, 11, 16])

data = np.logspace(0,63,64,base=2,dtype=unit64）

In [4]:
arr = np.random.rand(2,3) # 生成服从 [0, 1) 均匀分布 的随机浮点数 
# np.random.rand(d0, d1, d2, ...)
arr

array([[0.54297411, 0.41866181, 0.71147513],
       [0.9828776 , 0.20014091, 0.37916853]])

# 固定随机种子

In [5]:
np.random.seed(42) # the number 42 is just a popular “arbitrary” seed
print(np.random.rand(3))
# 每次都输出相同结果：[0.37454012 0.95071431 0.73199394]
# After seeding, all np.random.* functions produce a predictable sequence.

[0.37454012 0.95071431 0.73199394]


## Modern way (NumPy 1.17+)
- Instead of setting a global seed, you can now create independent random generators:

In [7]:
rng = np.random.default_rng(seed=42)
rng.random(3)   # reproducible but isolated sequence

array([0.77395605, 0.43887844, 0.85859792])

# 寻找数组 np.random.randint(1,25,size=(5,5))中所有的偶数，并将所有偶数替换为 0.

In [10]:
import numpy as np
a = np.random.randint(1,5,size=(5,5))
print(a)

[[1 4 1 3 4]
 [4 1 4 4 2]
 [1 4 3 4 1]
 [1 4 3 4 4]
 [4 3 3 1 2]]


In [11]:
for i in range(5):
    for j in range(5):
        a[i,j]=0 if a[i,j]%2==0 else a[i,j]
print(a)

[[1 0 1 3 0]
 [0 1 0 0 0]
 [1 0 3 0 1]
 [1 0 3 0 0]
 [0 3 3 1 0]]


# 利用normal方法生成正态分布的随机数组

In [12]:
import numpy as np
n1 = np.random.normal(0,10,10)
print('生成正态分布的随机数组：\n',n1)

生成正态分布的随机数组：
 [  0.63018429  -0.85705446   3.68099088  -7.54788284 -13.76269387
 -20.84345938  -6.43168272  15.56073689   6.31653277   7.23853198]


# 利用asarray方法 从已有的数组中创建数组
**numpy.asarray(a, dtype=None, order=None)**

In [13]:
import numpy as np
n1 = np.asarray([1,4,7])
print('通过列表 创建数组：\n',n1)

n2 = np.asarray([(1,4,7),(3,6,9)])
print('通过列表的元组创建数组：\n',n2)

n3 = np.asarray((1,4,7))
print('通过元组创建数组：\n',n3)

n4 = np.asarray(((1,4,7),(3,6,9)))
print('通过元组的元组创建数组：\n',n4)

通过列表 创建数组：
 [1 4 7]
通过列表的元组创建数组：
 [[1 4 7]
 [3 6 9]]
通过元组创建数组：
 [1 4 7]
通过元组的元组创建数组：
 [[1 4 7]
 [3 6 9]]


# frombuffer方法实现动态数组 从已有的数组中创建数组 （字符串转换为数组）

## numpy .frombuffer(buffer, dtype=float, count=-1, offset=0)

In [1]:
import numpy as np
I = b'Ilove Python'
print(type(I))

<class 'bytes'>


In [23]:
ar = np.frombuffer(I, dtype = 'S1')

print(ar)
print(type(ar))

[b'I' b'l' b'o' b'v' b'e' b' ' b'P' b'y' b't' b'h' b'o' b'n']
<class 'numpy.ndarray'>


In [24]:
# 'S1' 是 NumPy 的定长字节串（fixed-width byte string）类型，表示：
# S：byte string（不是 Unicode），元素类型是 numpy.bytes_/numpy.string_。
# 1：每个元素占 1 个字节（长度为 1 的字节串）。
#会把缓冲区 I 按逐字节切分成很多长度为 1 的字节串元素

<br>

## NumPy 里“字符串相关”的几种 dtype 讲清楚

### 1) 定长字节串：S<N>

- 含义：每个元素是定长 N 字节的 bytes（非 Unicode）。元素类型是 numpy.*bytes_*。
- 存储：恰好 N 个字节；不足会用 \x00（null）填充；超出会被截断。

In [12]:
a = np.array([b'hi', b'cat'], dtype='S4')  # 每个元素4字节
print(a.itemsize)  # 4
a           # b'hi\x00', b'cat\x00'
# 不足会用 \x00 码位填充（对用户不可见）

4


array([b'hi', b'cat'], dtype='|S4')

<br>

dtype=**'U'：存字符（Unicode）→ 类似 str**
    
dtype=**'S'：存字节（bytes）→ 显示会有 b'...'**

### 2) 定长 Unicode 串：U<N>

- 存储：每个码位通常占 4 字节（UCS-4，平台相关），因此 dtype='U10' 的 itemsize≈40。

In [14]:
b = np.array(['猫', '狗'], dtype='U3')  # 允许3个码位
print(b.itemsize)        # 通常 3*4 = 12

12


In [13]:
(b + '咪')        # 广播拼接，结果会自动 upcast 增宽

array(['猫咪', '狗咪'], dtype='<U4')

In [ ]:
# < 是字节序标记，可忽略

### 3) Python 对象字符串：object（dtype=object）

- 含义：数组里存放可变长 Python str 对象（或混合对象）。

In [16]:
c = np.array(['a'*10, 'b'*1000], dtype=object)
c

array(['aaaaaaaaaa',
       'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb

### 其他：自动扩宽（upcast）：拼接/赋值可能触发 dtype 自动加宽以容纳更长字符串：

In [19]:
x = np.array(['hi'], dtype='U2')
y = x + 'there'          # 结果 dtype 会变成 U7
y

array(['hithere'], dtype='<U7')

# 利用full_like创建以指定值“6”填充的数组

In [25]:
# numpy.full_like(a, fill_value, dtype=None, order='K', subok=True)
import numpy as np
ar = np.arange(5)
print('生成5个元素的数组：\n', ar)

生成5个元素的数组：
 [0 1 2 3 4]


In [26]:
n = np.full_like(ar,6)
print('用6填充后的同型数组：\n', n)

用6填充后的同型数组：
 [6 6 6 6 6]
